spring:
  application:
    name: albums-ws

  rabbitmq:
    username: user
    password: password

  devtools:
    restart:
      enabled: true

  bus:
    enabled: true
    refresh:
      enabled: true

  h2:
    console:
      path: /h2-console
      enabled: true
      settings.web-allow-others: true

#  datasource:
#    url: jdbc:mysql://localhost:3306/photo_app_albums?createDatabaseIfNotExist=true
#    username: root
#    password: peanutbutter

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:0}

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: ${LOG_FILE_NAME}

  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false